# Generated by Django 6.0.8 on 2026-08-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('symbol', models.CharField(blank=True, max_length=20, verbose_name='símbolo')),
                ('description', models.TextField(verbose_name='descrição')),
                ('color', models.CharField(default='#31E6FF', help_text='Cor hexadecimal. Ex.: #31E6FF', max_length=7, verbose_name='cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factrion',
                'verbose_name_plural': 'Factrions',
                'ordering': ('display_order', 'name'),
            },
        ),
    ]
