# Generated by Django 6.0.8 on 2026-08-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='network_id',
            field=models.CharField(blank=True, editable=False, max_length=9, unique=True, verbose_name='Registro FN'),
        ),
        migrations.AddField(
            model_name='operator',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='onboarding_step',
            field=models.CharField(choices=[('choose_faction', 'Escolher Facção'), ('cognitive_test', 'Teste Cognitivo'), ('choose_avatar', 'Escolher aparência'), ('completed', 'Concluído')], default='choose_faction', max_length=30),
        ),
        migrations.AddField(
            model_name='operator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
    ]
