# Generated by Django 6.0.8 on 2026-08-17 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('operators', '0002_operator_network_id_operator_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='identity.faction', verbose_name='Factrion'),
        ),
    ]
