# Generated by Django 6.0.8 on 2026-08-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_operator_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='presentation',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=10, verbose_name='apresentação'),
        ),
        migrations.AddField(
            model_name='operator',
            name='shirt_color',
            field=models.CharField(blank=True, choices=[('cyan', 'Ciano'), ('purple', 'Roxo'), ('green', 'Verde'), ('red', 'Vermelho'), ('yellow', 'Amarelo'), ('white', 'Branco')], max_length=20, verbose_name='cor da camiseta'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='onboarding_step',
            field=models.CharField(choices=[('choose_faction', 'Escolher Facção'), ('choose_avatar', 'Escolher aparência'), ('completed', 'Concluído')], default='choose_faction', max_length=30),
        ),
    ]
