# Generated by Django 6.0.8 on 2026-08-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpawnPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='código')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False, verbose_name='spawn padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ponto de Spawn',
                'verbose_name_plural': 'Pontos de Spawn',
                'ordering': ('name',),
            },
        ),
    ]
