# Generated by Django 6.0.8 on 2026-08-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('width', models.PositiveIntegerField(default=3200, verbose_name='largura')),
                ('height', models.PositiveIntegerField(default=2200, verbose_name='altura')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapas',
            },
        ),
        migrations.AddField(
            model_name='spawnpoint',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spawn_points', to='world.citymap', verbose_name='mapa'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(max_length=120)),
                ('image_path', models.CharField(help_text='Ex.: world/img/buildings/building_01.png', max_length=255, verbose_name='caminho da imagem')),
                ('x', models.IntegerField(verbose_name='posição X')),
                ('y', models.IntegerField(verbose_name='posição Y')),
                ('width', models.PositiveIntegerField(verbose_name='largura visual')),
                ('height', models.PositiveIntegerField(verbose_name='altura visual')),
                ('collision_offset_x', models.IntegerField(default=0, verbose_name='offset colisão X')),
                ('collision_offset_y', models.IntegerField(default=0, verbose_name='offset colisão Y')),
                ('collision_width', models.PositiveIntegerField(verbose_name='largura da colisão')),
                ('collision_height', models.PositiveIntegerField(verbose_name='altura da colisão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='world.citymap', verbose_name='mapa')),
            ],
            options={
                'verbose_name': 'Prédio',
                'verbose_name_plural': 'Prédios',
                'ordering': ('display_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('map', 'slug'), name='unique_building_slug_per_map')],
            },
        ),
    ]
