# Generated by Django 6.0.8 on 2026-08-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_citymap_spawnpoint_map_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='building',
            name='unique_building_slug_per_map',
        ),
        migrations.AddField(
            model_name='building',
            name='has_entrance',
            field=models.BooleanField(default=False, verbose_name='possui entrada'),
        ),
        migrations.AddField(
            model_name='building',
            name='interaction_height',
            field=models.PositiveIntegerField(default=32, verbose_name='altura da interação'),
        ),
        migrations.AddField(
            model_name='building',
            name='interaction_offset_x',
            field=models.IntegerField(default=0, verbose_name='offset interação X'),
        ),
        migrations.AddField(
            model_name='building',
            name='interaction_offset_y',
            field=models.IntegerField(default=0, verbose_name='offset interação Y'),
        ),
        migrations.AddField(
            model_name='building',
            name='interaction_width',
            field=models.PositiveIntegerField(default=48, verbose_name='largura da interação'),
        ),
    ]
